### ISSUE TITLE
Async callbacks in genserver, or separation of work and state?

### ISSUE THREAD

**Issue by matthewoden** [findmypast/vaultex#19]
I was experimenting with a vault visualizer CLI, tacking on `?list=true` to make the read operation turn into a list operation, and recursively expanding paths. But it didn't ever get very far, and after about five seconds, I started getting genserver timeouts.

Peeking at the code, it looks like the vault http calls are initiated as part of a GenServer `call` callback. Which is totally fine for fetching one or two secrets as part of an application. 

But for more than a few calls, it starts becoming a bottleneck. IIRC, a GenServer `call` expects a reply, so it doesn't free up the queue for new messages until the callback is resolved -  which means that every vault request is currently being handled serially. If a call has 20 other requests in front of it, it might timeout without ever getting a chance to talk to vault at all.

It also looks like the genserver is just for storing the token, and the vault url. Could these get moved into a separate store module? Something like `Vaultex.Store` with methods for `get_token`, `get_url` (and maybe `set_token`, `set_url`). Could even be an `Agent`.

Then http/read/write calls could fetch from the store without waiting on IO, and wouldn't be bottlenecked by access to the genserver process. Instead, they'd just be part of the calling process.

Alternatively, (if you'd prefer the genserver/client to be more of a brain) you could delegate to handle_info for the HTTP call:

``` Elixir
def handle_call({:action, data}, from, state) do
   Process.send(self(), {:action, data, from}) # delegate async action to handle_info
   
   # do any state updates here

   # return no_reply, so we can grab the next message and reply later in handle info.
   (:no_reply, state} 
end

def handle_info({:action, data, from}, state) do
   # Do the work, without blocking the call queue:
   #
   # Because nothing we do in the return depends on the result 
   # of this call, the the VM treats this as a side-effect. It 
   # returns immediately, letting us move on to the next message.
   result = some_async_call(data, state.url, state.token) 

   Genserver.reply(from, result) #reply to the original caller

   # any other state changes here

   (:no_reply, state} # always no_reply from info
end
```
But that'd have to be done for every HTTP call. Not the worst thing, just adds boilerplate.

I'd be happy to make a pull request for either direction.

**Comment by matthewoden** [comment]
There was a lot of silence on this issue - so I took the initiative, and spent some time this week with the holiday to see what this might look like.

Like I mentioned above, application doesn't seem to be used for much. So I planned on breaking out the vault HTTP API into a library module that the application could then call. Then we could let the application/genserver focus on stateful tasks, token storage and automatic lease renewal, etc. 

The results so far are here: https://github.com/matthewoden/libVault

- Provides read/write/list/delete and auth methods
- HTTP client is fully adaptable, a default adapter is provided, using Tesla.
	- Tesla means that httpoison, ibrowse, httpc clients get supported out of the box, with a wide range of dependency support. No more `override: true`!
- Auth Backends are fully adaptable, supporting custom mount paths.
	- AppRole
	- Azure
	- GitHub
	- GoogleCloud
	- JWT
	- Kubernetes
	- LDAP
	- UserPass
	- Token
	- Generic
- Secret Engines are fully adaptable. 
	- One engine adapter covers the 80% use case, since the API is so similar.
	- KVV2 is weird, so it gets a custom adapter.
- Additional API flexibility is provided with an additional "request" method. Renewing leases, updating configuration, anything users might need to cover their edge cases.
- Non-blocking concurrency - the library shouldn't be much more than a speedy broker, and move any/all bottlenecks to the vault instance.
	- Runs 126 tests in 1.6 seconds. Most of that is hitting a local bypass sever, but even the request pool is never bogged down.

...I ended up rewriting the whole thing from scratch. When possible, I'd prefer to make something better, rather than make something else. But adding adapters, and removing blocking calls (and frankly, the entire need for an application) ended up being too much of a change for a PR. 

If you have ideas on how we can end up with a single, killer vault library, I'm all ears. Otherwise, I'll probably toss this in one of my apps and test it against a production vault instance - then publish this out.

**Comment by AtebMT** [comment]
Hey Matthew,

Thanks for taking the time effort to look at improving this module, it's greatly appreciated. 

This codebase started off life as  `A very simple elixir client that authenticates, reads, writes and deletes secrets from HashiCorp's Vault.` The README still says that! It was intended to make it easy to do the basics. (Mainly because there was nothing else out there). It's grown a bit since then and provides more functionality (more authentication back-ends for example) but the key concept remains the same. In some use cases, this approach comes at a price of flexibility and performance.

Since your approach is a total re-write a PR - as your point out - is out of the equation. IMHO, This is really a different project. While it would be interesting to see how we could create a "single, killer vault library" time constraints mean that I would find it difficult to allocate too much time against this.

By all means create and publish a new project - variety and choice is essential.

Once again, thanks for your time and effort.
