### ISSUE TITLE
Vaultex should use envvar VAULT_SSL_VERIFY instead of SSL_SKIP_VERIFY

### ISSUE THREAD

**Issue by jwarnier** [findmypast/vaultex#20]
Official Ruby and CLI client both use the environment variable "VAULT_SSL_VERIFY", while Vaultex uses "SSL_SKIP_VERIFY".
Especially in environments where multiple languages implementations are used, this can be misleading.
Please align it.

Thanks

**Comment by AtebMT** [comment]
v0.6.2 updated with support for the new environment var.
