### ISSUE TITLE
Add docs describing the SSL_CERT_FILE environment variable

### ISSUE THREAD

**Issue by philss** [findmypast/vaultex#32]
Would be nice to have documentation for the environment variable `SSL_CERT_FILE` which provides a way to pass self signed certificates.

We could also change the name of this variable to something more related to Vault, like `VAULT_CACERT` as it is used in @sethvargo's projects (e.g: https://github.com/sethvargo/vault-kubernetes-authenticator/blob/2c8fe1e10fee698ad967518396455be2c13354cc/README.md).

For backward compatibility, we could use both env vars for a period of time, giving preference to the new one.
What do you think?

**Comment by sethvargo** [comment]
`VAULT_CACERT` is the [envvar that Vault reads](https://github.com/hashicorp/vault/blob/a54603039d5c38fcc2c9468f3beb29e1c1c2aca0/api/client.go#L28-L40)

**Comment by AtebMT** [comment]
Sure, that's a pretty straight forward change.

**Comment by AtebMT** [comment]
Done.
