### ISSUE TITLE
How to do writes with Vaultex

### ISSUE THREAD

**Issue by CrowdHailer** [findmypast/vaultex#5]
- Why is this library read only?
- How would you go about writing values in vault from Elixir programs?
- Would it be a pull request you are interested in to extend vaultex to also support writes?

Sorry if I have missed something obvious. I am relatively new to vault.

**Comment by sashman** [comment]
Hey @CrowdHailer, we haven't added the write functionality as we haven't needed it this far, however a PR would be very welcome!

A general approach for it would be to create a `lib/vaultex/write.ex` module similar to the `read.ex` and change the request to use [the write API for vault](reading-writing-and-listing-secrets)

**Comment by CrowdHailer** [comment]
Excellent. That is exactly what we have done in our [fork](https://github.com/chingventures/vaultex).

I will try and look at seeing what needs to be done to resolve the conflicts this week.

**Comment by sashman** [comment]
Hey @CrowdHailer are you still interested in having your write functionality merged in?

**Comment by sashman** [comment]
Hey again @CrowdHailer sorry about the delay, we've added write functionality in version 0.3.0 now. If it's okay I'll be closing this now.

**Comment by CrowdHailer** [comment]
Cheers, I'll check it out. apologies for not responding to earlier message. have been working on different issues
