### ISSUE TITLE
Add other authentication backends

### ISSUE THREAD

**Issue by hauleth** [findmypast/vaultex#6]
I am especially interested in:

- AppRole as it is never version of now deprecated AppID method
- Token as it is really handy in development

**Comment by smoak** [comment]
It looks like this [fork](https://github.com/chingventures/vaultex) supports token authentication.

**Comment by dmitryzuev** [comment]
AppRole authentication support:
https://github.com/findmypast/vaultex/pull/9

**Comment by sashman** [comment]
@hauleth the PR #9 has been merged into a new patch version, hope it's what you've been looking for. Can this issue be closed?

**Comment by hauleth** [comment]
It seem so. I will close it for now and I will create new issue in case of troubles.
